
let state={lang:localStorage.getItem('asb_lang')||'zh',route:'home',activeLesson:localStorage.getItem('asb_lesson')||'ai',progress:JSON.parse(localStorage.getItem('asb_progress')||'{}')};
function L(p){return p.split('.').reduce((o,k)=>o?.[k],I18N[state.lang])??p}
function save(){localStorage.setItem('asb_lang',state.lang);localStorage.setItem('asb_lesson',state.activeLesson);localStorage.setItem('asb_progress',JSON.stringify(state.progress))}
function pct(){return Math.round(Object.values(state.progress).filter(Boolean).length/LESSONS.length*100)}
function setRoute(r){state.route=r;scrollTo(0,0);render()}
function toggleLang(){state.lang=state.lang==='zh'?'en':'zh';save();render()}
function toast(m){let e=document.createElement('div');e.className='toast';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),1600)}
function nav(){let ns=[['home','nav.home'],['courses','nav.courses'],['free','nav.free'],['premium','nav.premium'],['tools','nav.tools'],['prompts','nav.prompts'],['community','nav.community'],['thailand','nav.thailand'],['impact','nav.impact']];return `<header class='topbar'><div class='wrap nav'><button class='brand' onclick="setRoute('home')"><span class='logo'>AI</span> Skill <span style='color:var(--blue)'>Bridge</span></button><nav class='navlinks'>${ns.map(([r,k])=>`<button class='${state.route===r?'active':''}' onclick="setRoute('${r}')">${L(k)}</button>`).join('')}<button class='lang' onclick='toggleLang()'>${state.lang==='zh'?'EN':'中文'}</button></nav></div></header>`}
function shell(c){return nav()+c+`<footer class='footer'><div class='wrap'><p>© 2026 AI Skill Bridge.</p></div></footer>`}
function home(){return shell(`<main><section class='hero'><div class='wrap hero-grid'><div><p class='eyebrow'>AI for Beginners</p><h1>${L('home.title')}</h1><p class='lead'>${L('home.lead')}</p><div class='btnrow'><button class='btn primary' onclick="setRoute('free')">${L('home.start')}</button><button class='btn secondary' onclick="setRoute('tools')">${L('home.tools')}</button><button class='btn secondary' onclick="setRoute('premium')">${L('home.premium')}</button></div></div><aside class='hero-card'><h2>${L('home.progress')}</h2><div class='progressbar'><div class='progressfill' style='width:${pct()}%'></div></div><p>${pct()}% completed</p><div class='grid two'><div class='card'><b>${LESSONS.length}</b><br>Free lessons</div><div class='card'><b>${TOOLS.length}</b><br>AI tools</div></div></aside></div></section><section class='section'><div class='wrap'><h2>${state.lang==='zh'?'從看得懂、做得到，到真的用得上。':'From understanding to practice to real use.'}</h2><div class='grid three'><article class='card'><span class='tag free'>Free</span><h3>${state.lang==='zh'?'免費入門':'Free Beginner'}</h3><p>${state.lang==='zh'?'讓 AI 小白從零開始。':'Start from zero.'}</p></article><article class='card'><span class='tag premiumtag'>Premium</span><h3>${state.lang==='zh'?'進階付費':'Premium'}</h3><p>${state.lang==='zh'?'研究、求職、創業分級課程。':'Research, career, startup tracks.'}</p></article><article class='card'><span class='tag communitytag'>Community</span><h3>${state.lang==='zh'?'討論社群':'Community'}</h3><p>${state.lang==='zh'?'讓使用者可以互相提問。':'Ask and share with peers.'}</p></article></div></div></section></main>`)}
function courses(){return shell(`<main class='page'><div class='wrap'><h1>${state.lang==='zh'?'課程地圖':'Course Roadmap'}</h1><div class='grid two'><article class='pricing'><span class='tag free'>Free</span><h2>${state.lang==='zh'?'免費入門路徑':'Free Path'}</h2><p class='price'>NT$0</p><button class='btn primary' onclick="setRoute('free')">${state.lang==='zh'?'進入':'Enter'}</button></article><article class='pricing'><span class='tag premiumtag'>Premium</span><h2>${state.lang==='zh'?'進階付費路徑':'Premium Path'}</h2><p class='price'>NT$499+</p><button class='btn secondary' onclick="setRoute('premium')">${state.lang==='zh'?'查看':'View'}</button></article></div></div></main>`)}
function free(){let l=LESSONS.find(x=>x.id===state.activeLesson)||LESSONS[0];return shell(`<main class='page'><div class='wrap'><h1>${state.lang==='zh'?'免費入門課程':'Free Beginner Course'}</h1><div class='dashboard'><aside><div class='panel'>${LESSONS.map(x=>`<button class='sidebtn ${x.id===l.id?'active':''}' onclick="state.activeLesson='${x.id}';save();render()"><span>${state.lang==='zh'?x.zhTitle:x.enTitle}</span><span>${state.progress[x.id]?'✓':''}</span></button>`).join('')}</div></aside><section>${lesson(l)}</section></div></div></main>`)}
function lesson(l){let html=`<article class='lesson'><div class='meta'><span class='tag free'>${l.level}</span></div><h2>${state.lang==='zh'?l.zhTitle:l.enTitle}</h2><p>${state.lang==='zh'?l.zhText:l.enText}</p>`;if(l.quiz){html+=`<div class='practice'><h3>${state.lang==='zh'?l.quiz.zhQ:l.quiz.enQ}</h3>${l.quiz.options.map((o,i)=>`<button class='quiz-option' onclick="quiz('${l.id}',${i},this)">${state.lang==='zh'?o.zh:o.en}</button>`).join('')}<div id='fb-${l.id}' class='feedback hidden'></div></div>`}if(l.zhTask){html+=`<div class='practice'><h3>${state.lang==='zh'?'練習':'Practice'}</h3><p>${state.lang==='zh'?l.zhTask:l.enTask}</p><textarea></textarea><button class='btn secondary' onclick="document.getElementById('ans-${l.id}').classList.add('show')">${state.lang==='zh'?'看參考答案':'Reveal answer'}</button><div id='ans-${l.id}' class='answer'>${state.lang==='zh'?l.zhAnswer:l.enAnswer}</div></div>`}html+=`<button class='btn primary' onclick="state.progress['${l.id}']=true;save();render()">${state.lang==='zh'?'完成':'Complete'}</button></article>`;return html}
function quiz(id,i,b){let l=LESSONS.find(x=>x.id===id),o=l.quiz.options[i];b.classList.add(o.correct?'correct':'wrong');let fb=document.getElementById('fb-'+id);fb.classList.remove('hidden');fb.textContent=(o.correct?L('misc.correct'):L('misc.wrong'))+' '+(state.lang==='zh'?l.quiz.zhExplain:l.quiz.enExplain)}
function premium(){return shell(`<main class='page'><div class='wrap'><h1>${state.lang==='zh'?'進階付費課程':'Premium Courses'}</h1><div class='grid three'>${PREMIUM.map(c=>`<article class='pricing'><span class='tag premiumtag'>Premium</span><h2>${state.lang==='zh'?c.zhTitle:c.enTitle}</h2><p>${state.lang==='zh'?c.zhDesc:c.enDesc}</p><p class='price'>${c.price}</p><a class='btn primary' href='https://gumroad.com/' target='_blank'>${state.lang==='zh'?'前往付款':'Go to payment'}</a></article>`).join('')}</div></div></main>`)}
function tools(){return shell(`<main class='page'><div class='wrap'><h1>${state.lang==='zh'?'AI 工具導航':'AI Tools'}</h1><div class='grid three'>${TOOLS.map(t=>`<article class='card'><div class='tool-logo'>${t[0][0]}</div><h3>${t[0]}</h3><p>${state.lang==='zh'?t[2]:t[3]}</p><a class='btn primary' href='${t[1]}' target='_blank'>${state.lang==='zh'?'開啟網站':'Open'}</a></article>`).join('')}</div></div></main>`)}
function prompts(){return shell(`<main class='page'><div class='wrap'><h1>Prompt Library</h1><div class='grid two'>${PROMPTS.map((p,i)=>`<article class='card'><span class='tag'>${p[0]}</span><div class='promptbox' id='p${i}'>${p[1]}</div><button class='btn secondary' onclick="navigator.clipboard.writeText(document.getElementById('p${i}').innerText);toast(L('misc.copied'))">Copy</button></article>`).join('')}</div></div></main>`)}
function community(){return shell(`<main class='page'><div class='wrap'><h1>${state.lang==='zh'?'討論區與 PPT 式看板':'Community & Slide Board'}</h1><div class='slide'><h3>${state.lang==='zh'?'我想用 AI 做報告，但不想讓它代替我思考，Prompt 應該怎麼寫？':'How can AI help with reports without replacing my thinking?'}</h3><div class='sticky-note'>Role + Task + Context + Verification</div></div></div></main>`)}
function thailand(){return shell(`<main class='page'><div class='wrap'><h1>${state.lang==='zh'?'泰國 Yunus Center AIT 學習成果區':'Thailand Learning Documentation'}</h1><p class='lead'>${state.lang==='zh'?'記錄青年百億海外圓夢基金 I-3-8 的學習歷程。':'Documentation for Youth Overseas Dream Fund Project I-3-8.'}</p></div></main>`)}
function impact(){return shell(`<main class='page'><div class='wrap'><h1>${state.lang==='zh'?'影響力模式':'Impact Model'}</h1><div class='grid three'><article class='card'><span class='tag free'>Access</span><h3>Free Learning</h3><p>Lower AI learning barriers.</p></article><article class='card'><span class='tag premiumtag'>Sustainability</span><h3>Premium Courses</h3><p>Support platform operation.</p></article><article class='card'><span class='tag communitytag'>Community</span><h3>Peer Learning</h3><p>Help users ask and share.</p></article></div></div></main>`)}
function render(){let r={home,courses,free,premium,tools,prompts,community,thailand,impact};document.getElementById('app').innerHTML=(r[state.route]||home)();save()}
addEventListener('DOMContentLoaded',render)
